#pragma once
// #define RGBLIGHT_EFFECT_BREATHING

#define TAPPING_TOGGLE 1

#define LED_POWER_PIN 24

#define ENCODER_RESOLUTION 2

#define OLED_BRIGHTNESS 32

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_WPM_ENABLE

#define FORCED_CROSS_HAND_MODIFIERS
